# Generated by Django 4.2.7 on 2026-04-13 09:37

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import portal.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_id', models.CharField(default=portal.models.generate_application_id, editable=False, max_length=20, unique=True)),
                ('study_number', models.CharField(blank=True, max_length=20, null=True)),
                ('learner_name', models.CharField(max_length=200)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('previous_school', models.CharField(blank=True, max_length=200)),
                ('previous_grade', models.CharField(blank=True, max_length=50)),
                ('parent_name', models.CharField(max_length=200)),
                ('parent_email', models.EmailField(max_length=254)),
                ('parent_phone', models.CharField(max_length=20)),
                ('parent_address', models.TextField()),
                ('emergency_contact', models.CharField(max_length=20)),
                ('emergency_contact_name', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('under_review', 'Under Review'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('waitlisted', 'Waitlisted')], default='pending', max_length=20)),
                ('application_date', models.DateTimeField(auto_now_add=True)),
                ('review_notes', models.TextField(blank=True)),
                ('decision_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-application_date'],
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade_number', models.IntegerField(choices=[(8, 'Grade 8'), (9, 'Grade 9'), (10, 'Grade 10'), (11, 'Grade 11'), (12, 'Grade 12')])),
                ('grade_name', models.CharField(max_length=50)),
                ('capacity', models.IntegerField(default=30, validators=[django.core.validators.MinValueValidator(1)])),
                ('available_spaces', models.IntegerField(default=30)),
                ('year', models.IntegerField(default=2026)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['grade_number'],
                'unique_together': {('grade_number', 'year')},
            },
        ),
        migrations.CreateModel(
            name='Stream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField()),
                ('subjects', models.TextField(help_text='List of main subjects in this stream')),
            ],
        ),
        migrations.CreateModel(
            name='Learner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('study_number', models.CharField(default=portal.models.generate_study_number, editable=False, max_length=20, unique=True)),
                ('pin', models.CharField(default=portal.models.generate_pin, editable=False, max_length=6)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField()),
                ('admission_status', models.CharField(choices=[('applied', 'Applied'), ('admitted', 'Admitted'), ('registered', 'Registered'), ('suspended', 'Suspended'), ('expelled', 'Expelled'), ('transferred', 'Transferred'), ('graduated', 'Graduated')], default='applied', max_length=20)),
                ('date_joined', models.DateField(auto_now_add=True)),
                ('parent_name', models.CharField(max_length=200)),
                ('parent_email', models.EmailField(max_length=254)),
                ('parent_phone', models.CharField(max_length=20)),
                ('application', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='learner_profile', to='portal.application')),
                ('grade', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='learners', to='portal.grade')),
                ('stream', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='learners', to='portal.stream')),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='FinancialInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tuition_fees', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('scholarship_status', models.CharField(choices=[('none', 'No Scholarship'), ('partial', 'Partial Scholarship'), ('full', 'Full Scholarship')], default='none', max_length=20)),
                ('scholarship_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('scholarship_details', models.TextField(blank=True)),
                ('bursary_status', models.CharField(choices=[('none', 'No Bursary'), ('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='none', max_length=20)),
                ('bursary_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('bursary_details', models.TextField(blank=True)),
                ('total_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('balance_due', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('payment_status', models.CharField(choices=[('paid', 'Fully Paid'), ('partial', 'Partially Paid'), ('unpaid', 'Unpaid'), ('overdue', 'Overdue')], default='unpaid', max_length=20)),
                ('last_payment_date', models.DateField(blank=True, null=True)),
                ('learner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='financial_info', to='portal.learner')),
            ],
            options={
                'verbose_name': 'Financial Information',
                'verbose_name_plural': 'Financial Information',
            },
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('exam_type', models.CharField(choices=[('midterm', 'Mid-Term Examination'), ('final', 'Final Examination'), ('test', 'Class Test'), ('assignment', 'Assignment'), ('quiz', 'Quiz'), ('practical', 'Practical Examination')], max_length=20)),
                ('marks', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('grade', models.CharField(max_length=2)),
                ('year', models.IntegerField()),
                ('term', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)])),
                ('date_taken', models.DateField()),
                ('teacher_remarks', models.TextField(blank=True)),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='portal.learner')),
            ],
            options={
                'ordering': ['-date_taken', 'subject'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('birth_certificate', 'Birth Certificate'), ('previous_report', 'Previous Year Progress Report'), ('id_document', 'ID/Passport Document'), ('proof_residence', 'Proof of Residence'), ('immunization', 'Immunization Records'), ('other', 'Other Document')], max_length=30)),
                ('file', models.FileField(upload_to=portal.models.document_upload_path)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('verified', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='portal.application')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.AddField(
            model_name='application',
            name='grade_applying',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='portal.grade'),
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.IntegerField()),
                ('subjects', models.TextField(help_text='Selected subjects')),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('incomplete', 'Incomplete')], default='pending', max_length=20)),
                ('rules_accepted', models.BooleanField(default=False)),
                ('rules_accepted_date', models.DateTimeField(blank=True, null=True)),
                ('registration_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fee_paid', models.BooleanField(default=False)),
                ('payment_date', models.DateTimeField(blank=True, null=True)),
                ('proof_of_registration', models.FileField(blank=True, null=True, upload_to='registration_proofs/')),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='portal.learner')),
                ('stream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='portal.stream')),
            ],
            options={
                'ordering': ['-academic_year'],
                'unique_together': {('learner', 'academic_year')},
            },
        ),
        migrations.CreateModel(
            name='ProgressReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('term', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)])),
                ('overall_average', models.DecimalField(decimal_places=2, max_digits=5)),
                ('class_position', models.IntegerField(blank=True, null=True)),
                ('total_learners', models.IntegerField(blank=True, null=True)),
                ('teacher_comments', models.TextField()),
                ('principal_comments', models.TextField(blank=True)),
                ('report_file', models.FileField(blank=True, null=True, upload_to='progress_reports/')),
                ('date_issued', models.DateField(auto_now_add=True)),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_reports', to='portal.learner')),
            ],
            options={
                'ordering': ['-year', '-term'],
                'unique_together': {('learner', 'year', 'term')},
            },
        ),
    ]
