# Generated by Django 4.2.7 on 2026-04-13 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(blank=True, max_length=20, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='stream',
            name='subjects_text',
            field=models.TextField(blank=True, help_text='Legacy: List of main subjects in this stream'),
        ),
        migrations.RemoveField(
            model_name='stream',
            name='subjects',
        ),
        migrations.AddField(
            model_name='stream',
            name='subjects',
            field=models.ManyToManyField(blank=True, related_name='streams', to='portal.subject'),
        ),
    ]
