# Generated by Django 4.2.7 on 2026-04-16 07:26

from django.db import migrations, models
import django.db.models.deletion
import portal.models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_subject_stream_subjects_text_remove_stream_subjects_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_id', models.CharField(default=portal.models.generate_teacher_id, editable=False, max_length=20, unique=True)),
                ('pin', models.CharField(default=portal.models.generate_teacher_pin, editable=False, max_length=6)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('employee_number', models.CharField(blank=True, max_length=20, unique=True)),
                ('hire_date', models.DateField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('grades', models.ManyToManyField(blank=True, related_name='teachers', to='portal.grade')),
                ('subjects', models.ManyToManyField(blank=True, related_name='teachers', to='portal.subject')),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.AddField(
            model_name='exam',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_exams', to='portal.teacher'),
        ),
    ]
