# Generated by Django 4.2.7 on 2026-04-29 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_alter_teacher_email_task_tasksubmission'),
    ]

    operations = [
        migrations.CreateModel(
            name='BursaryScholarshipRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_type', models.CharField(choices=[('bursary', 'Bursary'), ('scholarship', 'Scholarship')], max_length=20)),
                ('year', models.IntegerField()),
                ('code', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('suspended', 'Suspended'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('amount_allocated', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('amount_utilized', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funding_records', to='portal.learner')),
            ],
            options={
                'verbose_name': 'Bursary/Scholarship Record',
                'verbose_name_plural': 'Bursary/Scholarship Records',
                'ordering': ['-year', '-date_created'],
            },
        ),
    ]
