# Generated by Django 4.2.7 on 2026-05-04 12:35

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_bursaryscholarshiprecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('pending', 'Pending')], default='no', max_length=10)),
                ('academic_year', models.IntegerField()),
                ('term', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_status', to='portal.learner')),
            ],
            options={
                'ordering': ['academic_year', 'term', 'subject'],
                'unique_together': {('learner', 'subject', 'academic_year', 'term')},
            },
        ),
    ]
