# Generated by Django 4.2.7 on 2026-05-04 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0006_examstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examstatus',
            name='status',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('na', 'NA'), ('pending', 'Pending')], default='no', max_length=10),
        ),
    ]
